version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yiff
    versions:
    - 2.0.3
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.6
  - dependency-name: pm2
    versions:
    - 4.5.1
    - 4.5.4
    - 4.5.5
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: lodash
    versions:
    - 4.17.20
